# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Movieskip' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Movieskip

    pod 'Firebase/Firestore'
    pod 'Firebase/Auth'
    pod 'Firebase/Storage'
    pod 'Firebase/Core'
    pod 'SDWebImage', '~>4.4.2'
    pod 'JGProgressHUD', '~>2.0.3'
    pod 'SwiftyJSON', '~> 4.0'
    pod 'Alamofire', '~> 5.2'


end
